spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # Can be 'none', 'update', 'create', 'create-drop'. Use 'update' for development.
    show-sql: true      # Show SQL queries in the console for debugging
    properties:
      hibernate:
        format_sql: true  # Formats SQL queries for better readability in the console
        dialect: org.hibernate.dialect.MySQL8Dialect  # Use appropriate dialect for your DB version

  jackson:
    serialization:
      write-dates-as-timestamps: false  # Properly format LocalDate/LocalDateTime

server:
  port: 5050  # Application will run on port 8080 by default
  error:
    include-message: always  # Ensure that error messages are included in responses

logging:
  level:
    org:
      hibernate: DEBUG  # Set Hibernate logging to DEBUG for detailed SQL logs
